
CREATE TABLE lions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    creating_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_lion_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE TABLE_SEQUENCE (
    next_val BIGINT DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO TABLE_SEQUENCE VALUES (0);

CREATE TABLE cows (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    creating_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    lion_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_schedule_cow_lion FOREIGN KEY (lion_id) REFERENCES lions (id) ON DELETE CASCADE,
    INDEX idx_cow_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE goats (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    creating_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_modification_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    lion_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_schedule_goat_lion FOREIGN KEY (lion_id) REFERENCES lions (id) ON DELETE CASCADE,
    INDEX idx_goat_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE grass (
    id BIGINT NOT NULL AUTO_INCREMENT,
    creating_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    cow_id BIGINT,
    goat_id BIGINT,
    PRIMARY KEY (id),
    CONSTRAINT fk_schedule_grass_cow FOREIGN KEY (cow_id) REFERENCES cows (id) ON DELETE CASCADE,
    CONSTRAINT fk_schedule_grass_goat FOREIGN KEY (goat_id) REFERENCES goats (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
